FROM node:14

# Copy proto
WORKDIR /sc
COPY /sc .
# Install protobuf dependencies
RUN npm i
RUN npx hardhat compile

# Copy source and install dependencies
WORKDIR /frontend
COPY frontend/package.json .

RUN npm i
COPY frontend .

# Disable sourcemap
ENV GENERATE_SOURCEMAP=false

# Build and run source
RUN npm run build

USER root
RUN npm i -g serve
CMD serve -s build -l 5000
