FROM node:14

# Copy proto
WORKDIR /sc
COPY sc .
# Install protobuf dependencies
RUN npm i

RUN npx hardhat compile

# Install dependencies
WORKDIR /backend
COPY backend/package.json .
RUN npm i --legacy-peer-deps
# Build and run source
COPY backend .
RUN npm run build
CMD ["npm","run", "start:prod"]
