version: "3.2"

services:
  backend:
    image: node:14-alpine
    container_name: ntfs_empty_backend
    build:
      dockerfile: Dockerfile.empty
    command : "true"
    entrypoint : "true"

  client:
    image: node:14-alpine
    container_name: ntfs_empty_client
    build:
      dockerfile: Dockerfile.empty
    command : "true"
    entrypoint : "true"
